name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Check versions match
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          pkg_version=$(node -p "require('./package.json').version")
          manifest_version=$(node -p "require('./manifest.json').version")
          
          if [ "$tag" != "$pkg_version" ]; then
            echo "Error: Git tag ($tag) does not match version in package.json ($pkg_version)"
            exit 1
          fi
          
          if [ "$tag" != "$manifest_version" ]; then
            echo "Error: Git tag ($tag) does not match version in manifest.json ($manifest_version)"
            exit 1
          fi
          
          echo "Versions match: $tag"

      - name: Build
        id: build
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css
